projects:
  voyaahuikit:
    schemaPath: amplify/backend/api/voyaahuikit/build/schema.graphql
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/service-module/aws-current-itinerary.service.ts
        docsFilePath: src/graphql
        region: ap-south-1
        apiId: null
        maxDepth: 4
extensions:
  amplify:
    version: 3
